#!/usr/sbin/nft -f

# Delete only our table before rebuild, so reload never creates duplicates.
destroy table inet filter

table inet filter {
    chain output {
        type filter hook output priority filter; policy accept;
	    # Block any program trying to skip Pi-hole using external DNS on port 53.
        # Allow 127.0.0.0/8 so Pi-hole on 127.0.0.1 can still use Unbound.
        udp dport 53 ip daddr != 127.0.0.0/8 drop
        tcp dport 53 ip daddr != 127.0.0.0/8 drop
        # Same block for IPv6, allow only ::1 for local Unbound.
        udp dport 53 ip6 daddr != ::1 drop
        tcp dport 53 ip6 daddr != ::1 drop
    }
}